### PR TITLE
Cycle 4: Astropy CoCo Work (Brasseur)

### PR DESCRIPTION
**Pull request by ceb8**
Pull request to fund my Astropy CoCo and related work.

Still draft because I haven't worked out all the details.

As with my other grant the 2.5 year term of this funding request may include an international move on my part which may complicate things.

### CODE REVIEW

**Comment by kelle** [comment]
Please remove travel from this request.

**Comment by eteq** [comment]
Please react to this comment to vote on this proposal (👍, 👎, or no reaction for +0)

**Comment by bsipocz** [comment]
The inequality of the votes of this proposal and the others shows that it's not an OK avenue to vote for compensating committee membership on the individual level. There should be one proposal that includes paying all members equally (and then those who cannot take the money would not accept it, just as one does not accept it for grant reviews, but at least it's being offered equally)

**Comment by jdswinbank** [comment]
Hey @bsipocz — thanks, that's a really good point. I encourage folks to bear it in mind while deciding how to cast their votes, but we don't intend to change the overall process for the current funding cycle. We'll take account of this when planning how to proceed with Cycle 5.

**Comment by dhomeier** [comment]
+1 – perhaps also a good thing would be to set up suggestions whether proposals should preferably be split up by topic, or combined into people's work packages. I don't like writing proposals (but probably no one does ;-) and have thus combined everything as far as feasible, but of course this makes it more difficult to evaluate base on the individual tasks.

**Comment by jdswinbank** [comment]
I'm writing on behalf of Astropy's Finance Committee. We are pleased to be able to let you know that, following consultation with the community, we are able to approve this request. We can currently fund the one year of work in the amount of $6,000 (US). Funding beyond this amount will be contingent upon the availability of funds. (We will be using the full budgets of all of the approved requests to craft future grant and funding proposals.) We assume you will be using this full year 1 budget; if that is not the case, please contact us immediately.

Ana Gabela and I will be your contacts on the Finance Committee to facilitate this award. Please get in touch with us if you have any questions or concerns. Please do not reach out to NumFOCUS directly.

In addition, new to this funding cycle, is the assignment of a COTR (Contracting Officer's Technical Representative) to each funded project. This concept is borrowed from government funding agencies, although it is to be stressed that Astropy's goal is to make the COTR role as low-overhead as possible. The COTR’s primary responsibility is to make sure the work is happening at the expected pace and, if necessary, to be a liaison between the funded project and the Finance Committee or CoCo. The COTR for your project will be assigned shortly and we’ll also be sending out more details about how we see this working.

The next steps are:

- We will reach out through NumFOCUS, Astropy's Fiscal Sponsor, to Aperio to set up an “independent contractor agreement” (ICA; effectively a contract) and formal scope of work for the project.
- While this is in progress, the Finance Committee and the Coordination Committee will identify a COTR for each project. More information on this will be in the issue for your project once the COTR is identified.

We expect the work to be carried out between 2024-05-01 and 2025-04-30 (the “period of performance”). If you come to realize that the work will take more time than originally planned, you can apply for an extension following the procedure described at https://github.com/astropy/astropy-project/blob/main/finance/process/request-extension.md.

Congratulations — we are really looking forward to seeing you put these funds to good use!

**Pull request merged**
