### PR TITLE
Cycle 4: Astroquery & other maintenance (Ginsburg)

### PR DESCRIPTION
**Pull request by keflavich**
This proposal covers maintenance effort by me on astroquery, astropy.convolution, reproject, regions, and affiliated packages.

### CODE REVIEW

**Comment by kelle** [comment]
- Since this is a subaward and involves regular maintenance work, please consider submitting a 3 year request.
- This will be funding from NASA at full overhead rates, not 10%. Please adjust your budget accordingly.

**Comment by keflavich** [comment]
Thanks @Kelle.  I'll make both revisions.

**Comment by kelle** [comment]
Note: The Finance committee has received very detailed and official budget documents from the University of Florida in support of this FR.  The numbers agree with those in the text of the request.

**Comment by kelle** [comment]
Consider adding a minimum request. Budget numbers can be rough estimates.

**Comment by eteq** [comment]
Please react to this comment to vote on this proposal (👍, 👎, or no reaction for +0)

**Comment by kelle** [comment]
I'm writing on behalf of Astropy's Finance Committee regarding the outcome of this funding request. We are pleased to be able to let you know that, following consultation with the community, we are able to approve this request. We can currently fund the Year 1 amount of US$ 22,738.00 to carry out the project. Funding beyond this amount will be contingent upon the availability of funds. (We will be using the full budgets of all of the approved requests to craft future grant and funding proposals.) We assume you will be using this full year 1 budget, if that is not the case please contact us immediately.

Ana Gabela and I will be your contacts on the Finance Committee to facilitate this award. Please get in touch with us if you have any questions or concerns. Please do not reach out to NumFOCUS directly. Also, after merging this PR, I will open an issue where we can discuss progress on this project.

In addition, new to this funding cycle, is the assignment of a COTR (Contracting Officer's Technical Representative) to each funded project. This concept is borrowed from government funding agencies, although it is to be stressed that Astropy's goal is to make the COTR role as low-overhead as possible. The COTR’s primary responsibility is to make sure the work is happening at the expected pace and, if necessary, to be a liaison between the funded project and the Finance Committee or CoCo. The COTR for your project will be assigned shortly and we’ll also be sending out more details about how we see this working.

We will be in touch about getting this subaward setup with the University of Florida.

Congratulations --- we are really looking forward to seeing you put these funds to good use!

Kelle, on behalf of the Astropy Finance Committee

**Comment by kelle** [comment]
https://github.com/astropy/astropy-project/issues/419

**Pull request merged**
