### PR TITLE
Phase 3 Funding | Brasseur | Learn Notebooks

### PR DESCRIPTION
**Pull request by ceb8**
This is a funding request for myself, Clara Brasseur, to develop tutorial notebooks for Astropy Learn, as well as travel funding to attend Astro Hack Week 2022.

### CODE REVIEW

**Comment by kelle** [comment]
Looking forward to hearing/reading more about the tutorials you're interested in writing.

**Comment by jdswinbank** [comment]
Because the estimated total of all the proposals is a bit higher than the amount available for allocation, we suggest that you (@ceb8) provide a budget range - i.e., a "minimum for this project to be viable" and "maximum you could use effectively for this project".

**Comment by ceb8** [comment]
@jdswinbank  I added a minimum viable budget line in the document. The maximum is the amount I originally asked for.

**Comment by kelle** [comment]
Please react to this comment to vote on this proposal (👍, 👎, or no reaction for +0).

**Comment by jdswinbank** [comment]
Congratulations!  The community has expressed support for this FR, and the Finance Committee has determined it can be funded.  This FR has been approved for $6,600, to be funded from the NASA grant.

@eteq  is the Finance Committee member who will be supporting this project.  They will update this PR with the amount and then merge it, as well as being in contact with you to set up any necessary agreements and relevant Open Collective financial arrangements. They will also open a new issue where progress on this project can be discussed.

**Pull request merged**
