### PR TITLE
IDE Proposal: SACNAS 2020

### PR DESCRIPTION
**Pull request by eblur**
SACNAS holds a conference each year, which is
the ["largest multidisciplinary and multicultural STEM diversity event
in the country"](https://www.2020sacnas.org/).

This year, the event will be held in a virtual conference setting,
October 19-24. The conference features motivational keynote speakers,
science sessions that highlight students and scholars of color,
professional development sessions, and indigenous cultural
celebrations.

We will assemble a group Astropy Ambassadors to attend the
conference. Their goals will be to learn from talks and network with
SACNAS attendees.

### CODE REVIEW

**Comment by hamogu** [comment]
I think this proposal is realistic in that it aims to "network" this year with the goal to learn how to engage more next time. Does anyone know the fraction of participants broadly related to astronomy in this conference? Or is there a large fraction of e.g. students who might be interested in multiple topics? (It's probably hard to interest e.g. a PhD level mechanical engineer in astropy).

**Comment by hamogu** [comment]
This is somewhat similar to #125. Any idea which conference would be more appropriate if we can only pay for one?

**Comment by eblur** [comment]
Usually there is one Astrophysics focused science session each year. From my past experience, that draws 100-200 people to the room.

However, it covers all STEM topics, so there are people from many other fields (computer science and engineering in particular) that we might be missing if we only focus on physics and astronomy conferences.

**Comment by kelle** [comment]
The finance committee to fund this from the travel budget rather than from the IDEA initiative. Please move forward with planning.

**Comment by eblur** [comment]
Okay, should we all register ourselves and request reimbursement?

What are the procedures for reimbursement?

**Comment by kelle** [comment]
We have a purchasing card that I can put the registrations on. I can either register you or give you the CC info. If there's more than one person to register, I'd rather register everyone myself. Do you have a list of attendees?

**Comment by eblur** [comment]
The three people attending are in the PR text. I will email you and them with the information needed to register.

If anyone would like to take the 4th slot, please email me and/or Kelle by end of business today.

**Comment by hamogu** [comment]
@eblur: Did this happen? If so, can you leave a few lines of text as a comment here with lessons learned for the Astropy Project?

**Comment by hamogu** [comment]
@eblur: ping: : Did this conference happen as proposed? If so, can you leave a few lines of text of lessons learned or what to take away for the astropy project as a comment here?

**Comment by robelgeda** [comment]
The conference happened as proposed. Please see https://github.com/astropy/astropy-project/issues/125#issuecomment-927356022 for high level summary of the lessons learned from the conference.

**Comment by eblur** [comment]
In addition to Robel's report for NSBP (which holds equally true for SACNAS), we have the following

# Summary

I attended the SACNAS conference wearing two hats: one representing and recruiting for University of Michigan and the other representing Astropy. I was one of four Astropy collaboration members attending, including Robel Geda, Kelle Cruz, and Erik Tollerud. We browsed posters, spoke to individual students about their research, and attended an Astrophysics breakout room where we chatted and answered questions about astrophysics research and careers.

# Conclusions

Many students were aware of and used Astropy for their research but were not as aware about the process of contributing. Since SACNAS is a general science conference, I think we can gain a wider audience as well as potentially recruit computer science enthusiastic students by hosting a special science session about open source software. For now, we mostly interacted with astronomy students and gave a face to the Astropy project.

**Comment by jdswinbank** [comment]
Thanks @eblur & @robelgeda!

**Pull request closed without merging**
