### PR TITLE
Cycle 4 Funding: Spectroscopy Development Busy Week

### PR DESCRIPTION
**Pull request by kbwestfall**
Proposal requests funding to support a busy week for ~20 developers to push through development priorities for specutils and specreduce.

### CODE REVIEW

**Comment by kelle** [comment]
I think it will be useful to provide a budget range.  What is the minimum amount of funding which could be useful? Lots of the folks involved in this effort could potentially have travel support from other sources.  

Also, consider adding to the budget funds for both catering and space rental.  (Round numbers should be fine, I think it should just be explicitly in the proposal as a possible expense.)

**Comment by kelle** [comment]
For context, the total travel budget for the NASA grant is $60k.

**Comment by eteq** [comment]
Please react to this comment to vote on this proposal (👍, 👎, or no reaction for +0)

**Comment by dhomeier** [comment]
From the remarks in https://github.com/astropy/astropy-project/pull/399#issuecomment-2051168640 I'd take that this meeting is to take place following ADASS XXXII, and presumably in Malta as well; while the budgeting seems to assume it would be located at a tbd North American place. Could you clarify that?

**Comment by pllim** [comment]
> following ADASS XXXII

Wow, Malta? Unless they have secondary travel funding, I am a bit nervous about this.

**Comment by eteq** [comment]
@dhomeier @pllim  - I think that's a misunderstanding in #399 - there may be an ADASS event for spectroscopy, but it's not at all clear that's the same event as this, given that the text of this one indeed implies a home institution not ADASS.  So vote assuming that absent any clarification, not based on the comment in #399 by someone who is  not on this proposal.

**Comment by kbwestfall** [comment]
Apologies for the confusion, but @eteq basically clarified this.  The original concept for this was **not** a way to support the Malta ADASS follow-on that the spectroscopy dev group had already been discussing.  I see this as a distinct workshop at someone's home institution with the goals as given in the proposal.

**Comment by kelle** [comment]
Hi Kyle and team,

I'm writing on behalf of Astropy's Finance Committee regarding the outcome of your funding request. I will shortly open a new issue to track the progress.

We are pleased to be able to let you know that, following consultation with the community, we are able to approve this request. We can currently fund the minimum requested amount of $4000 (US) to carry out the project. Funding beyond this amount will be contingent upon the availability of funds. (We will be using the full budgets of all of the approved requests to craft future grant and funding proposals.) We assume you will be using this full year 1 budget, if that is not the case please contact us immediately.

Ana Gabela and I will be your contacts on the Finance Committee to facilitate this award. Please get in touch with us if you have any questions or concerns. Please do not reach out to NumFOCUS directly.

In addition, new to this funding cycle, is the assignment of a COTR (Contracting Officer's Technical Representative) to each funded project. This concept is borrowed from government funding agencies, although it is to be stressed that Astropy's goal is to make the COTR role as low-overhead as possible. The COTR’s primary responsibility is to make sure the work is happening at the expected pace and, if necessary, to be a liaison between the funded project and the Finance Committee or CoCo. The COTR for your project will be assigned shortly and we’ll also be sending out more details about how we see this working.

I will post instructions in the new issue for how to use the funds.

Congratulations --- we are really looking forward to seeing you put these funds to good use!

Kelle Cruz,
on behalf of the Astropy Finance Committee

**Pull request merged**
