### PR TITLE
STSCI proposal to add more support for ASDF serialization of astropy objects

### PR DESCRIPTION
**Pull request by perrygreenfield**
It's in the proposal!

### CODE REVIEW

**Comment by pllim** [comment]
Is this a repeat of the following?

* https://github.com/astropy/astropy-project/pull/348

**Comment by perrygreenfield** [comment]
Yes. It was suggested we re-propose for the regular funding requests rather than the "urgent" funding effort.

**Comment by pllim** [comment]
That's fine. I just want to make sure since it looks familiar. Thanks!

**Comment by perrygreenfield** [comment]
Correct.

**Comment by eteq** [comment]
Please react to this comment to vote on this proposal (👍, 👎, or no reaction for +0)

**Comment by jdswinbank** [comment]
I'm writing on behalf of Astropy's Finance Committee. We are pleased to be able to let you know that, following consultation with the community, we are able to approve this request. We can currently fund the one year of work in the amount of $19,200 (US). We assume you will be using this full budget; if that is not the case, please contact us immediately.

Ana Gabela and I will be the contacts on the Finance Committee for this award. Please get in touch with us if you have any questions or concerns. Please do not reach out to NumFOCUS directly.

In addition, new to this funding cycle, is the assignment of a COTR (Contracting Officer's Technical Representative) to each funded project. This concept is borrowed from government funding agencies, although it is to be stressed that Astropy's goal is to make the COTR role as low-overhead as possible. The COTR’s primary responsibility is to make sure the work is happening at the expected pace and, if necessary, to be a liaison between the funded project and the Finance Committee or CoCo. The COTR for this project will be assigned shortly and we’ll also be sending out more details about how we see this working.

The next steps are:

- Please make sure that the contractor (Elizabeth Madison) is registered with [Open Collective](https://opencollective.com/): this is the system they will use to submit their invoices for payment. Note that their invoices should be submitted through the [Astropy NASA](https://opencollective.com/astropy/projects/astropy-nasa) project.
- We will reach out through NumFOCUS, Astropy's Fiscal Sponsor, to set up an “independent contractor agreement” (ICA; effectively a contract) and formal scope of work for the project.
- While this is in progress, the Finance Committee and the Coordination Committee will identify a COTR for each project. More information on this will be in the issue for the project once the COTR is identified.

We expect the work to be carried out between 2024-05-01 and 2025-04-30 (the “period of performance”). If you come to realize that the work will take more time than originally planned, you can apply for an extension following the procedure described at https://github.com/astropy/astropy-project/blob/main/finance/process/request-extension.md.

Congratulations — we are really looking forward to seeing you put these funds to good use!

**Pull request merged**
