### PR TITLE
Cycle 4 Funding: Community Management(Beryl Kanali)

### PR DESCRIPTION
**Pull request by BerylKanali**
I am submitting a draft of my Cycle 4 funding request. The funding would allow me to continue my work as the Astropy Community Manager.

### CODE REVIEW

**Comment by eteq** [comment]
Please react to this comment to vote on this proposal (👍, 👎, or no reaction for +0)

**Comment by hamogu** [comment]
It is unclear to me what the community manager (together with OrgMycology). Even after reading the the linked drive document and and looking at the github repro with plots, I'm not sure how this benefits the astropy community. I liked the survey, but apart from that I've not not seen much engagement, e.g. the proposal mentions discourse. I've not see the community manager answering a single question so far and on slack a search turn up very little (except posts introducing herself and "please fill out the community survey"). There is no PR for the website, the community manager never attended e.g. the dev telecon. Maybe my ignorance is the problem here and I just don't understand what a community manager is supposed to do.

**Comment by pllim** [comment]
Is this some sort of a duplicate of #389 ?

**Comment by eteq** [comment]
@pllim - this is not a duplicate of #389, it's separate work by separate people (although they have been working together and presumably would continue to do so)

**Comment by BerylKanali** [comment]
> It is unclear to me what the community manager (together with OrgMycology). Even after reading the the linked drive document and and looking at the github repro with plots, I'm not sure how this benefits the astropy community. I liked the survey, but apart from that I've not not seen much engagement, e.g. the proposal mentions discourse. I've not see the community manager answering a single question so far and on slack a search turn up very little (except posts introducing herself and "please fill out the community survey"). There is no PR for the website, the community manager never attended e.g. the dev telecon. Maybe my ignorance is the problem here and I just don't understand what a community manager is supposed to do.

To address some of the concerns. OrgMycology was conracted to help me settle in my role by training and helping set up structures to help figure out what might work for the Astropy community so that after the first 6 months I would be able to serve the community more effectively with a better understanding of the needs and wants. For the 6 months most work was mostly leaned on understanding the community needs. For social media like discource, slack, facebook group and google groups there were a few posts across them but mainly we were looking at how we can consolidate the information across all those platforms to see which ones serve the community members at best. For the website that was put aside for the time being  since we were having a discussion on what is best cause of action there, whether the team working on it would need support to revamp and update it after we were done with the survey and DEI and got feedback from community members. [Here](https://docs.google.com/document/d/1pi7hVc_wJD9SR3LCJFNKFEZHFfvabHtcM_h0o7mVv4s/edit) is a document by OrgMycology that explain the work we were doing in the 6 months which was a point of reference for our deliverables as documented in the report attached in the proposal. I also understand that in the background things might be happening that community members are not aware of and it builds the confusion of what is going on(which has been discussed as well). Simply put most work in those 6 months was training, research and putting up structures for the community.

About the community manager role, it is common that the understanding of what a community manager does might not be clear since it spans a lot of things and changes time to time depending on the needs and whatever is going on in the community. Hopefully with the research findings and structures put in place together with OrgMycology a community manager will now be better placed at serving the community.

**Comment by pllim** [comment]
Re: https://github.com/astropy/astropy-project/pull/391#issuecomment-2052510582

Can you please clarify then whether it would make sense to accept one without the other? Seems like they are inter-dependent?

**Comment by AnaGabela** [comment]
Hi Beryl,

I'm writing on behalf of Astropy's Finance Committee regarding the outcome of your recent Funding Request.

We are sorry to report that your proposal could not be funded during this funding Cycle. We will be closing the FR as a result.

While the community vote was the primary driver of this, it is important to note that this likely does not reflect anything about you as a member of the Astropy Community. Rather, it reflects the specific balance of projects proposed this cycle, the available funds, and the priorities of this cycle’s funding sources relative to others.

We encourage you to read feedback in the thread above or other feedback you might have received via other means, and consider an FR for the next cycle with whatever modifications you think would help. You are also welcome to reach out to the Finance Committee for feedback if you would like.

Ana- on behalf of the Astropy Finance Committee

**Pull request closed without merging**
