### PR TITLE
Phase 3 funding: Homeier | General Maintainer

### PR DESCRIPTION
**Pull request by dhomeier**
Follow-up of my [Cycle II Proposal](https://github.com/astropy/astropy-project/blob/main/finance/proposal-calls/2021-proposal/Homeier-Core%2C_Spectroscopy.md) especially with increased support of general core maintainer work.
[Rendered proposal](https://github.com/dhomeier/astropy-project/blob/cycle3-dhomeier-maintenance/finance/proposal-calls/cycle3/Homeier-Maintainer.md)

### CODE REVIEW

**Comment by jdswinbank** [comment]
Because the estimated total of all the proposals is a bit higher than the amount available for allocation, we suggest that you (@dhomeier ) provide a budget range - i.e., a "minimum for this project to be viable" and "maximum you could use effectively for this project".

**Comment by dhomeier** [comment]
Do you just need the $24,000 identified as a minimum, or a breakdown what parts I would cut down on?

**Comment by jdswinbank** [comment]
I don't think a detailed breakdown is necessary, but some indication of what you regard as the “core targets” might help folks make an informed decision (I'm actually not sure if it means specifically the work on Astropy core — excluding affiliated packages — or just the parts of the proposal you feel are most important).

**Comment by aaryapatil** [comment]
Please react to this comment to vote on this proposal (👍, 👎, or no reaction for +0)

**Comment by jdswinbank** [comment]
Congratulations!  The community has expressed support for this FR, and the Finance Committee has determined it can be funded.  This FR has been approved for $42,240, to be funded from the Moore grant.

@eteq  is the Finance Committee member who will be supporting this project.  They will update this PR with the amount and then merge it, as well as being in contact with you to set up any necessary agreements and relevant Open Collective financial arrangements. They will also open a new issue where progress on this project can be discussed.

**Pull request merged**
