### PR TITLE
Phase 3 Funding: Astropy Maintainer Mentoring Program Proposal (Aperio Software)

### PR DESCRIPTION
**Pull request by astrofrog**
Still a draft - the scope and budget will be determined by whether and how long our Cycle II funding is extended for.

### CODE REVIEW

**Comment by eteq** [comment]
Because the estimated total of all the proposals is a bit higher than the amount available for allocation, we suggest that you (@astrofrog) provide a budget range - i.e., a "minimum for this project to be viable" and "maximum you could use effectively for this project".

**Comment by kelle** [comment]
Please react to this comment to vote on this proposal (👍, 👎, or no reaction for +0).

**Comment by mhvk** [comment]
Are there any examples of a mentor/mentee pair that have happened already?

**Comment by astrofrog** [comment]
@mhvk - no not yet, we hope to start pairing mentees and mentors in a few months, and before the end of 2022 (we will do this as part of extended Cycle II funding)

**Comment by jdswinbank** [comment]
Congratulations!  The community has expressed support for this FR, and the Finance Committee has determined it can be funded.  This FR has been approved for $6,450, to be funded from the Moore grant.

@kelle is the Finance Committee member who will be supporting this project.  They will update this PR with the amount and then merge it, as well as being in contact with you to set up any necessary agreements and relevant Open Collective financial arrangements. They will also open a new issue where progress on this project can be discussed.

**Pull request merged**
