### PR TITLE
Roadmap 2022

### PR DESCRIPTION
**Pull request by ceb8**
### Purpose:

Updating the Roadmap document per discussion at the Astropy Coordination meeting.

Notes from the Roadmap breakout session (which include a copy of the notes from the full group discussion) are [here](https://docs.google.com/document/d/1b2VcyesgnAugF36sfTFNyTBKMdCP9wgWx7b23ubO4y8/edit?usp=sharing).

See last year's PR for details about the Roadmap's origin: https://github.com/astropy/astropy-project/pull/220

### Order of operations:
- This PR is finalized and merged
- Meta issues created and tagged in this (astropy-project) repo
- Question added to the PR checklist in the writing a "what's new" section suggesting the user consider if their PR is related to the Roadmap.

### Feedback:
- This PR is open for comment **until 25 April 2022**
- Consider what on here has been solved and what issues are missing in your area of specialty

### CODE REVIEW

**Comment by kelle** [comment]
It's great to see some items being removed because WE DID THEM!  But it makes me sad that they are just being deleted. Would it be possible to have a companion "completed" page with a compilation of the completed bullets?

**Comment by ceb8** [comment]
@kelle Oooh! I like that idea. It also solves and issue @pllim and I were discussing about comparing with older versions.

**Comment by pllim** [comment]
Re: companion -- Like `roadmap/completed/roadmap_NNNN.md`, where `NNNN` is the year?

**Review by pllim — APPROVED** [review]
LGTM. Thanks!

**Comment by ceb8** [comment]
@kelle I just realized this was never merged, can you merge it?

**Pull request merged**
