### PR TITLE
Add proposals

### PR DESCRIPTION
**Pull request by eteq**
This adds a space for and info about the existing large grants to the Astropy project and their associated proposals..

### CODE REVIEW

**Review by kelle — APPROVED** [review]

**Comment by kelle** [comment]
Since we're working on updating the docs, might be a good time to finish this one off as well.

**Comment by jdswinbank** [comment]
Great! But a few comments:

- It'd be nice to make the filenames a bit more specific. At the moment, we only have one NASA ROSES proposal, but maybe that'll change in future so it probably makes sense to call the file something like `2020_nasa_roses` or similar.
- Documents should link to the GitHub issues on which the work to acquire the funds was carried out. So that's #161 for ROSES, etc.
- Do we really want this to be “successful proposals”? Don't we also want to keep track of proposals that were _unsuccessful_, so that we can learn from them? What about grants that weren't the result of a proposal process?
- Can we define “large”?

**Review by aaryapatil — APPROVED** [review]
Agree with @jdswinbank's comments above. Otherwise the text looks good - nice to have all the proposal documents in one place.

**Comment by hamogu** [comment]
Suggestion: In addition to having our proposals available for astropy, put them here: https://www.ogrants.org/

Having them in out github repro or as a link to a google drive (as in https://github.com/astropy/astropy-project/issues/161 for the NASA proposal) *might* be enough for astropy community members to find them, but contributing them to a more general "open collected proposals" repository for other institutions or projects, who might have less experience with grant writing than our community, to find them. If the PI or finance committee agree, I can do the step of uploading them, but I don't want to do that without agreement, since it's not clear who have the copyright to the proposal. Probably all of us, but certainly the PI, so with their approval, I don't have to waste time on meditating on copyright law (not my preferred past time....)

**Review by jdswinbank — APPROVED** [review]
Sorry for taking so long to notice this hanging out at the bottom of my inbox.

**Comment by jdswinbank** [comment]
Also added Moritz's suggestion to our upcoming meeting agenda.

**Comment by pllim** [comment]
Does this need more follow up. I see approvals.

**Pull request merged**
