### PR TITLE
Add drawio file for project infrastructure

### PR DESCRIPTION
**Pull request by pllim**
The version added via this PR would generate this diagram:

astropy_infrastructure

cc @embray

Also added to https://zenodo.org/record/4390110#.X-NX_dhKiUk

### CODE REVIEW

**Comment by pllim** [comment]
Needed edit: Benchmarks is split into `astropy-benchmarks` and `coordinates-benchmarks`.

**Comment by pllim** [comment]
Ideas to reduce maintenance burden:

* Reduce scope of some of the packages; i.e., stop accepting new features. Also see #159
* Plan to retire some, if possible. For example: Docker images for CircleCI.
* Automate some parts of the maintenance work.

**Comment by pllim** [comment]
For this particular PR to add a diagram, I think @embray said he has plans to clean it up and then get that version merged. Please correct me if I misunderstood.

**Comment by nstarman** [comment]
> Ideas to reduce maintenance burden:
> 
> * Reduce scope of some of the packages; i.e., stop accepting new features. Also see #159
> * Plan to retire some, if possible. For example: Docker images for CircleCI.
> * Automate some parts of the maintenance work.

* Recruit more maintainers, with roles limited to specific packages ?

**Comment by pllim** [comment]
Re: https://github.com/astropy/astropy-project/pull/122#issuecomment-718374218

Yes, that is also a possibility but not actionable until we know the funding situation more (Moore? pun?).

**Comment by pllim** [comment]
Probably outdated by now and there is Zenodo link added to OP.

**Pull request closed without merging**
