### PR TITLE
Cycle 4 Funding: Array API and astrowidgets

### PR DESCRIPTION
**Pull request by mwcraig**
This funding request would support the adoption of the Python array API in `ccdproc`/`CCDData`/`NDData`. It would also fund the finalization of a 1.0 release of astrowidgets.

### CODE REVIEW

**Comment by mwcraig** [comment]
Independent contractor. My formal retirement date at MSUM is 12/31/2024, so that seems more straightforward.

**Comment by mwcraig** [comment]
That report is excellent @nstarman -- thanks for bringing it to my attention, @mhvk!

**Comment by jdswinbank** [comment]
While obviously we'd love to fund this for the full amount listed, if we need to squeeze the budget is there a minimum number of hours that would make sense?

**Comment by eteq** [comment]
Please react to this comment to vote on this proposal (👍, 👎, or no reaction for +0)

**Comment by pllim** [comment]
Re: Array API -- Will you be working on these too?

* #15073
* #16286

**Comment by mwcraig** [comment]
Definitely the first of those, not as sure about the second one. I haven't read it thoroughly.

**Comment by jdswinbank** [comment]
I'm writing on behalf of Astropy's Finance Committee. We are pleased to be able to let you know that, following consultation with the community, we are able to approve this request. We can currently fund the one year of work in the amount of $11,250 (US). Funding beyond this amount in future years will be contingent upon the availability of funds. (We will be using the full budgets of all of the approved requests to craft future grant and funding proposals.) We assume you will be using this full year 1 budget; if that is not the case, please contact us immediately.

Ana Gabela and I will be your contacts on the Finance Committee to facilitate this award. Please get in touch with us if you have any questions or concerns. Please do not reach out to NumFOCUS directly.

In addition, new to this funding cycle, is the assignment of a COTR (Contracting Officer's Technical Representative) to each funded project. This concept is borrowed from government funding agencies, although it is to be stressed that Astropy's goal is to make the COTR role as low-overhead as possible. The COTR’s primary responsibility is to make sure the work is happening at the expected pace and, if necessary, to be a liaison between the funded project and the Finance Committee or CoCo. The COTR for your project will be assigned shortly and we’ll also be sending out more details about how we see this working.

I understand the funds allocated are insufficient for the full scope of your proposal. Rather than have the Finance Committee select from the various options you presented, we suggest that you discuss this and agree a course of action with the COTR when assigned.

The next steps are:

- Please make sure that you are registered with [Open Collective](https://opencollective.com/): this is the system you will use to submit your invoices for payment. Note that your invoices should be submitted through the [Astropy NASA](https://opencollective.com/astropy/projects/astropy-nasa) project.
- We will reach out through NumFOCUS, Astropy's Fiscal Sponsor, to set up an “independent contractor agreement” (ICA; effectively a contract) and formal scope of work for the project.
- While this is in progress, the Finance Committee and the Coordination Committee will identify a COTR for each project. More information on this will be in the issue for your project once the COTR is identified.

We expect the work to be carried out between 2024-05-01 and 2025-04-30 (the “period of performance”). If you come to realize that the work will take more time than originally planned, you can apply for an extension following the procedure described at https://github.com/astropy/astropy-project/blob/main/finance/process/request-extension.md.

Congratulations — we are really looking forward to seeing you put these funds to good use!

**Comment by mwcraig** [comment]
Wonderful, thanks for the good news!

**Pull request merged**
