### PR TITLE
Funding 2021: Astropy maintainer mentoring program

### PR DESCRIPTION
**Pull request by Cadair**
This proposal is to design and document a maintainer (role holder) mentoring program and then coordinate it for the first year.

### CODE REVIEW

**Comment by kelle** [comment]
This looks amazing! So glad to see this idea! 

Would it be in scope to add something about updating/improving/augmenting existing documentation? I think what I’m envisioning is a maintainer handbook that lives in the relevant package repo. And infrastructure which could even eventually get added to the package template.

**Comment by Cadair** [comment]
@kelle I think that probably is a bit out of scope, although gathering feedback (or contributions) from the mentors/mentees on what documentation isn't clear or is lacking would definitely be part of this.

**Comment by eteq** [comment]
Please react to this comment to vote on this proposal (:+1:, :-1:, or no reaction for +0)

**Comment by jdswinbank** [comment]
Congratulations @Cadair !  This proposal has the support of the Astropy Community and has been awarded $15,000 to implement.  This PR will be merged, and you can contact finance@astropy.org or reach out on Slack to arrange financial details (see more details in the email to astropy-dev).

**Pull request merged**
