### PR TITLE
Phase 3 Funding: Patil, White, Strubbe | PASEA

### PR DESCRIPTION
**Pull request by aaryapatil**
Draft FR for running a Python/AstroPy workshop at the Pan-African School for Emerging Astronomers 2022.

@heidiawhite

### CODE REVIEW

**Comment by kelle** [comment]
Because the estimated total of all the proposals is a bit higher than the amount available for allocation, we suggest that you (@aaryapatil ) provide a budget range - i.e., a "minimum for this project to be viable" and "maximum you could use effectively for this project".

**Comment by aaryapatil** [comment]
@kelle We have updated our budget and added more justification for costs. 

Would appreciate feedback if anyone has thoughts!

**Comment by aaryapatil** [comment]
We want to note the following, in case anyone is curious about our instructor team!

All sessions at PASEA are co-led and co-taught by an African and non-African member of the instructor team. This ensures that every phase of the students' learning maintains local perspectives and cultural context. We have 8 African instructors (originating from different countries in Africa) on our instructor team. These team members located in Africa have already secured their travel funding.

**Comment by aaryapatil** [comment]
Please react to this comment to vote on this proposal (👍, 👎, or no reaction for +0)

**Comment by mhvk** [comment]
Would be helpful to have a better idea about what the other funding sources contribute; ideally, astropy enables the astropy-related content.

**Comment by mhvk** [comment]
That is great! But if Dunlap is already providing instructor travel, what would the additional astropy-specific funding be for?

**Comment by heidiawhite** [comment]
I submitted the comment too early and have since provided specific details regarding intended use of the astropy funding. Would it be helpful to describe the curriculum we would be featuring that is astropy-specific?

**Comment by mhvk** [comment]
Thanks, I now read the edited comment; I was mainly wondering about the line in the budget for instructor travel. Why is this necessary if Dunlap already covers it? Or are there two separate schools?

**Comment by heidiawhite** [comment]
Ah, Dunlap funding will only cover travel costs for instructors which are UofT affiliated. So, for Dr. Strubbe, we are tasked with seeking funding beyond Dunlap.

Aarya Patil joined our team recently (to help develop programming for an online Python workshop for PASEA alumni) and her travel had not been included in our Dunlap grant application so she will also require outside funding.

It's important to note that PASEA features an adaptive curriculum. We adapt our curriculum to meet students' interests and learning needs both leading up to and during the school. And recently we have received lots of feedback from students that they are keen to develop Python programming and data science skills. Therefore, we are allocating much more school time (roughly half of the PG stream programming) to this Python/AstroPy workshop. Aarya Patil has been an amazing new addition to our instructor team and with this recent evolution in the curriculum her attendance and expertise in Zambia in October is critical.

**Comment by mhvk** [comment]
OK, that makes sense!

**Comment by kelle** [comment]
Congratulations!  The community has expressed support for this FR, and the Finance Committee has determined it can be funded.  This FR has been approved for $11,550, to be funded from the Moore grant.

@eteq is the Finance Committee member who will be supporting this project.  They will update this PR with the amount and then merge it, as well as being in contact with you to set up any necessary agreements and relevant Open Collective financial arrangements. They will also open a new issue where progress on this project can be discussed.

**Pull request merged**
