### PR TITLE
Phase 3 Funding: Learn Astropy Full Stack Development (Jonathan Sick)

### PR DESCRIPTION
**Pull request by jonathansick**
This is a Phase 3 funding request for my myself, Jonathan Sick, to maintain and develop new capabilities for the [Learn Astropy](https://learn.astropy.org) website and the related infrastructure that publishes and indexes content.

### CODE REVIEW

**Comment by kelle** [comment]
I am very interested in being a significant part of this effort. My contribution would be covered by my Funding Request (#285).

**Comment by eteq** [comment]
Because the estimated total of all the proposals is a bit higher than the amount available for allocation, we suggest that you (@jonathansick) provide a budget range - i.e., a "minimum for this project to be viable" and "maximum you could use effectively for this project".

**Comment by jonathansick** [comment]
@kelle would you like to be listed in the team section of the proposal? Anyone else from Learn Astropy? (happy to add of course; just not sure what the convention is for these propsals).

@eteq will do. My initial range was based on expected and best case availability, but I'll rephrase in terms of how many hours/dollars I think it might take to accomplish different projects so we (Astropy) can prioritize better.

**Comment by kelle** [comment]
Please react to this comment to vote on this proposal (👍, 👎, or no reaction for +0)

**Comment by jdswinbank** [comment]
Congratulations!  The community has expressed support for this FR, and the Finance Committee has determined it can be funded.  This FR has been approved for $24,000, to be funded from the NASA grant.

@aaryapatil is the Finance Committee member who will be supporting this project.  They will update this PR with the amount and then merge it, as well as being in contact with you to set up any necessary agreements and relevant Open Collective financial arrangements. They will also open a new issue where progress on this project can be discussed.

**Pull request merged**
